name: SBOM Generation

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  release:
    types: [published]

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SBOM for TypeScript packages
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: sbom-typescript.spdx.json
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate SBOM for Go modules
        if: hashFiles('services/**/go.mod') != ''
        run: |
          # Install Syft
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          
          # Generate SBOM for each Go module
          for dir in services/*/; do
            if [ -f "$dir/go.mod" ]; then
              module_name=$(basename "$dir")
              syft packages "$dir" --output spdx-json --file "sbom-go-${module_name}.spdx.json"
            fi
          done

      - name: Generate SBOM for Docker images
        if: github.event_name == 'release'
        run: |
          # Install Syft
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          
          # Generate SBOM for published images
          syft packages ghcr.io/mmanjos/obraflow-planning-service:latest --output spdx-json --file sbom-docker-planning.spdx.json
          syft packages ghcr.io/mmanjos/obraflow-work-service:latest --output spdx-json --file sbom-docker-work.spdx.json
          syft packages ghcr.io/mmanjos/obraflow-resource-service:latest --output spdx-json --file sbom-docker-resource.spdx.json

      - name: Upload SBOM to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: sbom-typescript.spdx.json

      - name: Upload Go SBOMs as artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sbom-go-modules
          path: sbom-go-*.spdx.json
          retention-days: 30

      - name: Upload Docker SBOMs as artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sbom-docker-images
          path: sbom-docker-*.spdx.json
          retention-days: 30
